spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: "!QAZ2wsx"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource




#整合Mybatis

mybatis:
  #  扫描数据持久对应的实体类 路径 Package级别
  type-aliases-package: com.jason.wy.demodao.Dao.DO
  #  mybatis 对应的 .xml文件路径
  mapper-locations: classpath:mapper/*.xml
  #  多层级目录  mapper-locations: classpath:mapper/**/**.xml
  config-location: classpath:mybatis-config.xml


regCenter:
  serverList: localhost:2181
  namespace: elastic-job-jason2

simpleJob:
  cron: "*/5 * * * * ?"
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

dataflowJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou


